version: '3'

services:
  guess-code-ui:
    build:
      context: ./src/GuessCodeUI
      dockerfile: Dockerfile
    image: guess-code-ui
    container_name: guess-code-ui
    ports:
      - "3000:80"
    networks:
      - guess-network